[package]
name = "queueleuleu"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
fern = { version = "0.6.0", features = ["colored"] }
http = "0.2.6"
hyper = "0.14.16"
log = "0.4.14"
slack-morphism-hyper="0.25"
slack-morphism-models="0.25"
slack-morphism="0.25"
tokio = "1.15.0"
